spring.application.name=trainlab
# ===============================
# = BANCO DE DADOS POSTGRESQL =
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/trainlabv2
spring.datasource.username=postgres
spring.datasource.password=0910
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = JPA / HIBERNATE =
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostra SQL no console (bom para estudo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true